/**
 * Resolve product stills. Prefer compressed md/thumb variants generated by:
 *   npm run optimize:product-images
 * then refresh the manifest with npm run sync:product-images
 */

import {
  productImageUrl,
  productImageThumbUrl,
  productImageMdUrl,
} from '../data/productImageManifest'

/**
 * @param {string} companyId
 * @param {{ id?: string, image?: string } | null} cell
 * @param {{ image?: string } | null} line
 * @param {'thumb' | 'md' | 'full'} [size]
 */
export function resolveProductImage(companyId, cell, line, size = 'md') {
  if (cell?.image) return cell.image
  if (line?.image) return line.image
  if (!cell?.id) return null
  if (size === 'thumb') {
    return (
      productImageThumbUrl(companyId, cell.id) ||
      productImageMdUrl(companyId, cell.id) ||
      productImageUrl(companyId, cell.id)
    )
  }
  if (size === 'full') return productImageUrl(companyId, cell.id)
  return (
    productImageMdUrl(companyId, cell.id) ||
    productImageUrl(companyId, cell.id)
  )
}
